### ISSUE TITLE
Doesn't pass all RubySpec specs

### ISSUE THREAD

**Issue by chrisseaton** [djberg96/pr-zlib#11]
I replaced the native zlib implementation in the JRuby+Truffle project with pr-zlib. We run RubySpec to check our compatibility with Ruby, so this is now indirectly running pr-zlib against RubySpec.

There are a handful of failures, but it seems to be that there's nothing that's fundamentally broken, this is fantastic!

Here are the tags (failing specs):

https://github.com/jruby/jruby/tree/master/spec/truffle/tags/library/zlib

I'll be working through these and will let you know when pr-zlib passes all of RubySpec.

**Comment by djberg96** [comment]
Cool. Just send me the PR's that fix the specs and I'll merge them.

**Comment by djberg96** [comment]
@chrisseaton Any updates?

**Comment by chrisseaton** [comment]
Sorry no update. I don't think we've fixed any more tags, as we haven't found them to be blocking anything important.

**Comment by djberg96** [comment]
Going to close this for now since there haven't been any updates and doesn't appear to be a blocker.
