### ISSUE TITLE
The pr-zlib-1.0.4 tag contains commits which are not on master

### ISSUE THREAD

**Issue by eregon** [djberg96/pr-zlib#13]
Hello,
the pr-zlib-1.0.4 tag contains commits which are not on master.

For example, commit 5f24219f843173a0aa267b71562753d8392ac533 is only available form the tag and not on master.

Could you:
```
git checkout master
git merge --ff-only pr-zlib-1.0.4
git push
```
to push those commits to the master branch as well?

**Comment by djberg96** [comment]
I pushed it up. Thanks for catching that.
