### ISSUE TITLE
Possible nil buffer in gzfile_read

### ISSUE THREAD

**Issue by nirvdrum** [djberg96/pr-zlib#14]
I've encountered an issue in `gzfile_read` attempting to read the offset of an uninitialized buffer (`@gz.z.buf.offset`). Unfortunately, I haven't been able to reduce to a simple use case. I can, however, observe the issue when testing the [minitar](https://github.com/halostatue/minitar) gem.

I fully admit these reproduction steps are not ideal, but it should illustrate the issue:

1. `git clone https://github.com/halostatue/minitar.git`
2. `cd minitar`
3.  `git checkout 3acdc06d182cbd2205ec1acd1619f3d011cf36ca` # master as of the writing of this issue.
4. `echo "gem 'pr-zlib'" >> Gemfile`
5. `bundle install`
6. `sed -i "s@require 'zlib'@require 'pr/zlib'@" test/test_tar_input.rb` # update require statement to use pr/zlib
7. `bundle exec rake`

If you run the same above tests on a clean checkout, thus using the stock zlib implementation, you'll see the tests pass fine. When run with pr-zlib, you'll see `NoMethodError: undefined method `offset' for nil:NilClass`.

**Comment by djberg96** [comment]
@phasis68 Any ideas?

**Comment by nirvdrum** [comment]
FWIW, I added the following to `gzfile_read`:

```
if @gz.z.buf.nil?
    @gz.z.buf = Bytef.new(0.chr * len)
end
```

That "fixes" the issue. But, I have no idea if that's an appropriate fix or not. Or whether I'm even fixing it in the correct location.

**Comment by djberg96** [comment]
@nirvdrum If you send me a PR I'll merge it.

**Comment by djberg96** [comment]
Fixed in master. Will be part of the next release, thanks!
