### ISSUE TITLE
[WIP] Make it faster

### ISSUE THREAD

**Issue by djberg96** [djberg96/pr-zlib#3]
Right now pr-zlib is something like 100x slower than the C version. While I understand that raw C will be faster than Ruby, I think we can do better.

I've created a "speedier" branch where we can experiment with speed improvements. Please use that.

**Comment by djberg96** [comment]
@phasis68 Do you have any suggestions for optimization?

**Comment by phasis68** [comment]
integer arithmetic and bit operation of ruby is very slow.
I think that bit operation functions like send_bits, bi_reverse are the optimization target.

**Comment by djberg96** [comment]
@phasis68 I don't think I was aware of that. How do you optimize arithmetic and bit operations in Ruby? I've been doing some research but haven't found anything definitive.

**Comment by phasis68** [comment]
That is the limitation of Ruby.
The support of native data format and direct arithmetic operation are required.

**Comment by djberg96** [comment]
Then how do we make those methods faster?

**Comment by phasis68** [comment]
As you know, the current implementation is optimized for C language.
Some sort of memoization using hash or array might be helpful to speed up.

**Comment by chrisseaton** [comment]
I did a little benchmarking myself. I concentrated on a loop as tight as possible, to exaggerate the effects, so I used `adler32`.

![slowdown](https://cloud.githubusercontent.com/assets/341094/11516141/811df9c8-9879-11e5-9e64-0ab5994f8541.png)

I see `pr-zlib` as being almost 3000x slower than native here, but only 1645x slower when run on JRuby. When you run on my implementation of Ruby, JRuby+Truffle, the slowdown is 'only' 200x. So a good optimiser can make a difference here.

```ruby
require 'zlib'
#require 'pr/zlib'

s = ''

10_000.times{ |x|
  s += "Now is the time for #{x} good men to come to the aid of their country."
}

loop do
  start = Time.now
  100.times do
    Zlib.adler32(s)
  end
  puts Time.now - start
end
```

**Comment by djberg96** [comment]
I tried some basic memoization techniques, but they ended up being *slower* than the original code. I guess hashtable lookups are more expensive than the arithmetic operations.

**Comment by phasis68** [comment]
I committed a patch to "speedier" branch

**Comment by djberg96** [comment]
@phasis68 Thanks! We're definitely making progress.

Master:
```
       user     system      total        real
write  7.900000   0.020000   7.920000 (  7.918475)
read  3.310000   0.010000   3.320000 (  3.332646)
```

Speedier branch prior to your last commit:
```
       user     system      total        real
write  6.650000   0.020000   6.670000 (  6.672667)
read  2.170000   0.010000   2.180000 (  2.180857)
```

Speedier branch after your last commit:
```
       user     system      total        real
write  6.610000   0.020000   6.630000 (  6.629036)
read  1.030000   0.000000   1.030000 (  1.042275)
```

**Comment by djberg96** [comment]
Note that I merged these updates into master for 1.0.3, but I'll leave this issue open for now for any future optimizations.

**Comment by djberg96** [comment]
I'm seeing a small improvement if we add the `frozen_string_literal: true` pragma, for the reads anyway.

**Comment by djberg96** [comment]
Closing as I don't know how to make it any faster at this point.
