### ISSUE TITLE
Rails 3.0.7 Ruby 1.9.2 - TypeError: allocator undefined for Zlib::ZStream

### ISSUE THREAD

**Issue by springbok** [djberg96/pr-zlib#5]
Hi,

I'm trying to use pr-zlib in my Rails app but I'm getting the following error:

TypeError: allocator undefined for Zlib::ZStream
	from /usr/jobbeat/bundler/ruby/1.9.1/gems/pr-zlib-1.0.2/lib/pr/zlib.rb:635:in `new'
	from /usr/jobbeat/bundler/ruby/1.9.1/gems/pr-zlib-1.0.2/lib/pr/zlib.rb:635:in `initialize'
	from /var/www/rails/jobbeat/lib/jobbeat/compressed_document.rb:14:in `new'
	from /var/www/rails/jobbeat/lib/jobbeat/compressed_document.rb:14:in `uncompress_document'
	from /var/www/rails/jobbeat/app/models/document.rb:160:in `document_contents'
	from (irb):33
	from /usr/jobbeat/bundler/ruby/1.9.1/gems/railties-3.0.7/lib/rails/commands/console.rb:44:in `start'
	from /usr/jobbeat/bundler/ruby/1.9.1/gems/railties-3.0.7/lib/rails/commands/console.rb:8:in `start'
	from /usr/jobbeat/bundler/ruby/1.9.1/gems/railties-3.0.7/lib/rails/commands.rb:23:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

I get this in irb after doing the following:
require 'pr/zlib'
Zlib::Inflate.new

I've got v1.0.2 install via my gem file.

**Comment by phasis68** [comment]
I cannot reproduce this issue.

**Comment by chrisseaton** [comment]
I can't reproduce either.

**Comment by djberg96** [comment]
The only thing I can think of is some sort of conflict between the zlib that ships with Ruby and pr-zlib. But, if you're using the stdlib version of zlib, you shouldn't need pr-zlib.

**Comment by chrisseaton** [comment]
stdlib zlib is loaded by ActiveSupport, so I guess also by anything using Rails.

**Comment by springbok** [comment]
Thank you for looking into this for me. I'm having issues with the stdlib zlib when deflating/inflating some document files, for some reason I get "incorrect data check" errors on some documents. I was hoping to use pr-zlib to see if I get the same issues and if not to use it instead. I'm willing to forgo some performance to get rid of these errors.

So pr-zlib can not be used at the same time stdlib zlib, if this is the case and ActiveSupport loads it then really it can not be used in Rails?

**Comment by djberg96** [comment]
I was able to duplicate this by adding it to a Rails gemfile, running bundle install, firing up a rails console, and then running the code above.

@springbok I don't think there's a workaround unless you want to dig into the Rails source and remove the zlib require statement by hand. There's nothing we can do on this end, sorry.
