### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by chrisseaton** [djberg96/pr-zlib#6]
Is there a licence on this code? I couldn't find one.

**Comment by djberg96** [comment]
Since @phasis68 is the primary author of this gem, I think he should decide. For what it's worth the rb-readline library is BSD, so I'm guessing he may choose the same here.

**Comment by phasis68** [comment]
I don't care about the license.
In my opinion, I'd like to follow zlib License because this is zlib.
https://en.wikipedia.org/wiki/Zlib_License

**Comment by djberg96** [comment]
I was not aware zlib had its own license. Sounds like a good idea to me.

**Comment by djberg96** [comment]
Ok, set the license to "zlib" in the gemspec and added a license section to the README. It will be part of the next release.

**Comment by chrisseaton** [comment]
Thank you very much - this is a great library.
